# Generated by Django 4.0.4 on 2022-05-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_users_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_email',
            field=models.EmailField(help_text='eg. volodymyr.di@gmail.com', max_length=200, unique=True),
        ),
    ]
