# Generated by Django 4.0.4 on 2022-05-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_users_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
