# Generated by Django 2.2.12 on 2022-05-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(upload_to='ev_images/')),
                ('event_text', models.CharField(max_length=300)),
            ],
        ),
    ]
