# Generated by Django 4.0.4 on 2022-05-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=300)),
                ('image', models.ImageField(null=True, upload_to='blog_images/')),
            ],
        ),
    ]
