# Generated by Django 4.0.4 on 2022-05-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='user_id',
            new_name='user',
        ),
    ]
