# Generated by Django 4.0.4 on 2022-05-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_post_id_postcomment_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('comment_date',)},
        ),
        migrations.AddField(
            model_name='postcomment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
