# Generated by Django 4.0.4 on 2022-06-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_postcomment_options_postcomment_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={},
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.TextField(max_length=3000),
        ),
    ]
