# Generated by Django 4.0.4 on 2022-06-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_postcomment_options_alter_postcomment_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
